name: CMake GoogleTest CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Used the matrix strategy to build on multiple operating systems
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      #build-and-test-ubuntu:
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      #with:
      #  submodules: true # If GoogleTest is a submodule

      - name: Install dependencies (MacOS only)
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Setup CMake and Ninja
        uses: ashutoshvarma/setup-ninja@master # This action also installs CMake
        with:
          version: 1.13.1 # Specify Ninja version 1.13.1

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.14 # Use a specific version for stability
        with:
          cmake-version: 4.1.1

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: cmake -B build -G Ninja -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --parallel 4

      - name: Run Tests
        run: ctest --test-dir build --verbose --output-on-failure --parallel 4
